#!/bin/sh

[ -z "$1" ] && echo "Usage: $0 'drama-title'" && exit
base_url="https://asianembed.io"
title=$(echo "$1" | sed 's/ /-/g')
searchurl="$base_url/search.html?keyword=$title"
cresult=$(curl -s "$searchurl")
lresult=$(echo "$cresult" | grep -Eo "\/videos.*[0-9]+\"" | sed "s/\"//g")
tresult=$(echo "$cresult" | shup -t "div[name]" | sed "s/   //g;/^[[:space:]]*$/d;s/Episode.*//g")
[ ! "$lresult" ] && echo "No results found" && exit || echo "$lresult" > dralinks.txt
echo "$tresult" > dratitles.txt
ffinder="pik"
promp=$(pr -m -t -w 180 dratitles.txt dralinks.txt | $ffinder | grep -o "/videos.*")
rm dralinks.txt dratitles.txt
[ ! "$promp" ] && exit
epnum=$(echo "$promp" | grep -Eo "episode\-[0-9]+" | sed "s/episode\-//g")
promp=$(echo "$promp" | sed 's/episode\-[0-9]*//g')
#for((i=1;i<=$epnum;i++))
i=1
while [ "$i" -lt $((epnum+1)) ]
do
echo "Episode $i"
i=$((i+1))
done > epslist.txt

choice=$($ffinder < epslist.txt | grep -Eo "[0-9]+")
rm epslist.txt
eplink="$base_url${promp}episode-$choice"

video_url=$(curl -s "$eplink" | sed -nE 's_^[[:space:]]*<iframe src="([^"]*)".*_\1_p' | sed 's/^/https:/g')
secret_key='3933343232313932343333393532343839373532333432393038353835373532'
iv='39323632383539323332343335383235'
ajax_url="$base_url/encrypt-ajax.php"
ajax=$(printf "%s" "$video_url" | sed -nE 's/.*id=(.*)&title.*/\1/p' | openssl enc -e -aes256 -K "$secret_key" -iv "$iv" | base64)
data=$(curl -s -H "X-Requested-With:XMLHttpRequest" "$ajax_url" -d "id=$ajax" | sed -e 's/{"data":"//' -e 's/"}/\n/' -e 's/\\//g')
video_link=$(printf '%s' "$data" | base64 -d | openssl enc -d -aes256 -K "$secret_key" -iv "$iv" | sed -e 's/\].*/\]/' -e 's/\\//g' | tr '{|}' '\n' | sed -nE 's/\"file\":"([^"]*)".*label.*P.*/\1/p')

echo "Loading video..."
mpv "$video_link"
