#!/bin/sh

ffinder="pik"
[ -z "$1" ] && echo "Specify a title to search!" && exit
search=$(echo "$1" | sed "s/\s/\+/g")
link="http://libgen.rs/search.php?req=$search&open=0&res=25&view=simple&phrase=1&column=title"

curlout=$(curl -s "$link")

ids=$(echo "$curlout" | grep -Eo "id=.[0-9]+" | sed 's/id=//g;10q')
[ ! "$ids" ] && echo "No results found." && exit
#|| echo "$ids" > libids.txt
for i in $ids; do
    echo "$curlout" | shup -t "a[$i]" | head -n 1
done > libnames.txt
echo "$curlout" | grep -o "http://library.lol/main/.*this" | sed "s/'.*//g;10q" > liburls.txt

promp=$(pr -m -t -w 180 libnames.txt liburls.txt | $ffinder | grep -o "http.*")
[ ! "$promp" ] && echo "You exited" && exit
rm libnames.txt liburls.txt

cpromp=$(curl -s "$promp")
finallink=$(echo "$cpromp" | grep -o 'http.*GET' | sed '1!d;s/\">GET//g') && echo "Downloading... Please wait"
exten=$(echo "$cpromp" | shup "a[href]" | grep -Eo '[A-Za-z]*\>\"' | sed '1!d;s/\"//g')
curl -o "$search.$exten" -s "$finallink" && echo "$search.$exten ---- Download finished!"
